import {
  BarChart,
  Users,
  Award,
  GitBranch,
  Briefcase,
  Calendar,
  FileText,
  FileCheck,
  DollarSign,
  BookOpen,
  ClipboardList,
  MessageSquare,
  StickyNote,
  CheckSquare,
  Wallet,
  Bell,
  Megaphone,
  Shield,
  Settings,
  Database,
  Download,
  Eye,
  Edit,
  Trash2,
  Plus,
  Filter,
  Download as DownloadIcon,
  Upload,
  UserCheck,
  Mail,
  Phone,
  TrendingUp,
  Target,
  Lock,
  PieChart,
  Activity,
  FileSpreadsheet,
} from "lucide-react";

/**
 * Comprehensive Permission Categories for CRM System
 * Each module has granular CRUD permissions
 */
export const permissionCategories = {
  "CRM Dashboard": [
    {
      id: "crm_dashboard_view",
      label: "View Dashboard",
      icon: BarChart,
      description: "Access and view CRM dashboard analytics",
    },
    {
      id: "crm_dashboard_widgets",
      label: "Customize Widgets",
      icon: Settings,
      description: "Add, remove, and arrange dashboard widgets",
    },
    {
      id: "crm_dashboard_reports",
      label: "View Reports",
      icon: PieChart,
      description: "Access dashboard reports and insights",
    },
    {
      id: "crm_dashboard_export",
      label: "Export Dashboard Data",
      icon: DownloadIcon,
      description: "Download dashboard data and reports",
    },
    {
      id: "crm_dashboard_analytics",
      label: "Advanced Analytics",
      icon: Activity,
      description: "Access detailed analytics and trends",
    },
  ],

  "Leads Management": [
    {
      id: "leads_view_all",
      label: "View All Leads",
      icon: Eye,
      description: "View all leads in the system",
    },
    {
      id: "leads_view_own",
      label: "View Own Leads",
      icon: Users,
      description: "View only assigned leads",
    },
    {
      id: "leads_create",
      label: "Create New Leads",
      icon: Plus,
      description: "Add new leads to the system",
    },
    {
      id: "leads_edit",
      label: "Edit Leads",
      icon: Edit,
      description: "Modify existing lead information",
    },
    {
      id: "leads_delete",
      label: "Delete Leads",
      icon: Trash2,
      description: "Remove leads from the system",
    },
    {
      id: "leads_assign",
      label: "Assign Leads",
      icon: UserCheck,
      description: "Assign leads to team members",
    },
    {
      id: "leads_import",
      label: "Import Leads",
      icon: Upload,
      description: "Bulk import leads from files",
    },
    {
      id: "leads_export",
      label: "Export Leads",
      icon: DownloadIcon,
      description: "Export lead data",
    },
    {
      id: "leads_contact",
      label: "Contact Leads",
      icon: Mail,
      description: "Send emails and messages to leads",
    },
    {
      id: "leads_convert",
      label: "Convert to Client",
      icon: TrendingUp,
      description: "Convert leads to clients",
    },
    {
      id: "leads_status_change",
      label: "Change Lead Status",
      icon: CheckSquare,
      description: "Update lead status and stages",
    },
    {
      id: "leads_notes",
      label: "Manage Lead Notes",
      icon: StickyNote,
      description: "Add and edit notes on leads",
    },
  ],

  Champions: [
    {
      id: "champions_view",
      label: "View Champions",
      icon: Award,
      description: "View top performing leads/clients",
    },
    {
      id: "champions_manage",
      label: "Manage Champions",
      icon: Edit,
      description: "Add or remove champion status",
    },
    {
      id: "champions_analytics",
      label: "Champion Analytics",
      icon: BarChart,
      description: "View champion performance metrics",
    },
    {
      id: "champions_rewards",
      label: "Manage Rewards",
      icon: Award,
      description: "Set up and manage reward programs",
    },
  ],

  "Pipeline Management": [
    {
      id: "pipeline_view",
      label: "View Pipeline",
      icon: GitBranch,
      description: "Access sales pipeline overview",
    },
    {
      id: "pipeline_stages_manage",
      label: "Manage Pipeline Stages",
      icon: Settings,
      description: "Create, edit, and delete pipeline stages",
    },
    {
      id: "pipeline_deals_create",
      label: "Create Deals",
      icon: Plus,
      description: "Add new deals to pipeline",
    },
    {
      id: "pipeline_deals_edit",
      label: "Edit Deals",
      icon: Edit,
      description: "Modify existing deals",
    },
    {
      id: "pipeline_deals_delete",
      label: "Delete Deals",
      icon: Trash2,
      description: "Remove deals from pipeline",
    },
    {
      id: "pipeline_deals_move",
      label: "Move Deals Between Stages",
      icon: GitBranch,
      description: "Change deal stages",
    },
    {
      id: "pipeline_forecast",
      label: "View Sales Forecast",
      icon: TrendingUp,
      description: "Access revenue forecasting",
    },
    {
      id: "pipeline_reports",
      label: "Pipeline Reports",
      icon: FileSpreadsheet,
      description: "Generate pipeline performance reports",
    },
  ],

  "Client Management": [
    {
      id: "clients_view_all",
      label: "View All Clients",
      icon: Eye,
      description: "View all client records",
    },
    {
      id: "clients_view_own",
      label: "View Own Clients",
      icon: Users,
      description: "View only assigned clients",
    },
    {
      id: "clients_create",
      label: "Create New Clients",
      icon: Plus,
      description: "Add new clients to the system",
    },
    {
      id: "clients_edit",
      label: "Edit Clients",
      icon: Edit,
      description: "Modify client information",
    },
    {
      id: "clients_delete",
      label: "Delete Clients",
      icon: Trash2,
      description: "Remove client records",
    },
    {
      id: "clients_documents",
      label: "Manage Client Documents",
      icon: FileText,
      description: "Upload and manage client files",
    },
    {
      id: "clients_communication",
      label: "Client Communication",
      icon: MessageSquare,
      description: "Send emails and messages to clients",
    },
    {
      id: "clients_contracts",
      label: "Manage Contracts",
      icon: FileCheck,
      description: "Create and manage client contracts",
    },
    {
      id: "clients_billing",
      label: "View Billing Information",
      icon: DollarSign,
      description: "Access client billing and payment data",
    },
  ],

  "Channel Integration": [
    {
      id: "channels_view",
      label: "View Channels",
      icon: GitBranch,
      description: "View integrated communication channels",
    },
    {
      id: "channels_configure",
      label: "Configure Channels",
      icon: Settings,
      description: "Set up and configure integrations",
    },
    {
      id: "channels_email",
      label: "Email Integration",
      icon: Mail,
      description: "Integrate and use email channels",
    },
    {
      id: "channels_phone",
      label: "Phone Integration",
      icon: Phone,
      description: "Integrate phone systems",
    },
    {
      id: "channels_social",
      label: "Social Media Integration",
      icon: Megaphone,
      description: "Connect social media platforms",
    },
  ],

  "HRM Dashboard": [
    {
      id: "hrm_dashboard_view",
      label: "View HRM Dashboard",
      icon: BarChart,
      description: "Access HR analytics dashboard",
    },
    {
      id: "hrm_dashboard_employee_stats",
      label: "Employee Statistics",
      icon: Users,
      description: "View employee statistics and metrics",
    },
    {
      id: "hrm_dashboard_attendance_overview",
      label: "Attendance Overview",
      icon: Calendar,
      description: "View attendance summaries",
    },
    {
      id: "hrm_dashboard_reports",
      label: "Generate HR Reports",
      icon: FileText,
      description: "Create and download HR reports",
    },
  ],

  "Team Management": [
    {
      id: "team_view",
      label: "View Teams",
      icon: Users,
      description: "View all teams and members",
    },
    {
      id: "team_create",
      label: "Create Teams",
      icon: Plus,
      description: "Create new teams",
    },
    {
      id: "team_edit",
      label: "Edit Teams",
      icon: Edit,
      description: "Modify team information",
    },
    {
      id: "team_delete",
      label: "Delete Teams",
      icon: Trash2,
      description: "Remove teams",
    },
    {
      id: "team_assign_members",
      label: "Assign Team Members",
      icon: UserCheck,
      description: "Add or remove team members",
    },
    {
      id: "team_set_leader",
      label: "Set Team Leaders",
      icon: Award,
      description: "Assign team leadership roles",
    },
  ],

  "Attendance Management": [
    {
      id: "attendance_view_all",
      label: "View All Attendance",
      icon: Eye,
      description: "View attendance records of all employees",
    },
    {
      id: "attendance_view_own",
      label: "View Own Attendance",
      icon: Calendar,
      description: "View personal attendance records",
    },
    {
      id: "attendance_mark",
      label: "Mark Attendance",
      icon: CheckSquare,
      description: "Record daily attendance",
    },
    {
      id: "attendance_edit",
      label: "Edit Attendance",
      icon: Edit,
      description: "Modify attendance records",
    },
    {
      id: "attendance_approve",
      label: "Approve Attendance",
      icon: UserCheck,
      description: "Approve attendance regularization requests",
    },
    {
      id: "attendance_reports",
      label: "Generate Attendance Reports",
      icon: FileSpreadsheet,
      description: "Create attendance reports",
    },
  ],

  "Leave Management": [
    {
      id: "leave_view_all",
      label: "View All Leaves",
      icon: Eye,
      description: "View all employee leave requests",
    },
    {
      id: "leave_view_own",
      label: "View Own Leaves",
      icon: Calendar,
      description: "View personal leave history",
    },
    {
      id: "leave_apply",
      label: "Apply for Leave",
      icon: Plus,
      description: "Submit leave applications",
    },
    {
      id: "leave_approve",
      label: "Approve/Reject Leaves",
      icon: UserCheck,
      description: "Process leave requests",
    },
    {
      id: "leave_cancel",
      label: "Cancel Leaves",
      icon: Trash2,
      description: "Cancel approved leaves",
    },
    {
      id: "leave_types_manage",
      label: "Manage Leave Types",
      icon: Settings,
      description: "Create and edit leave categories",
    },
    {
      id: "leave_balance",
      label: "View Leave Balance",
      icon: Calendar,
      description: "Check available leave balance",
    },
  ],

  "Employee Management": [
    {
      id: "employee_view_all",
      label: "View All Employees",
      icon: Users,
      description: "Access all employee profiles",
    },
    {
      id: "employee_view_basic",
      label: "View Basic Info",
      icon: Eye,
      description: "View basic employee information",
    },
    {
      id: "employee_create",
      label: "Add New Employees",
      icon: Plus,
      description: "Onboard new employees",
    },
    {
      id: "employee_edit",
      label: "Edit Employee Data",
      icon: Edit,
      description: "Modify employee information",
    },
    {
      id: "employee_delete",
      label: "Delete Employees",
      icon: Trash2,
      description: "Remove employee records",
    },
    {
      id: "employee_salary_view",
      label: "View Salary Information",
      icon: DollarSign,
      description: "Access employee salary details",
    },
    {
      id: "employee_documents",
      label: "Manage Employee Documents",
      icon: FileText,
      description: "Upload and manage employee files",
    },
    {
      id: "employee_promote",
      label: "Promote Employees",
      icon: TrendingUp,
      description: "Process employee promotions",
    },
    {
      id: "employee_transfer",
      label: "Transfer Employees",
      icon: GitBranch,
      description: "Transfer employees between departments",
    },
  ],

  "Department Management": [
    {
      id: "department_view",
      label: "View Departments",
      icon: Briefcase,
      description: "View all departments",
    },
    {
      id: "department_create",
      label: "Create Departments",
      icon: Plus,
      description: "Add new departments",
    },
    {
      id: "department_edit",
      label: "Edit Departments",
      icon: Edit,
      description: "Modify department information",
    },
    {
      id: "department_delete",
      label: "Delete Departments",
      icon: Trash2,
      description: "Remove departments",
    },
    {
      id: "department_assign_head",
      label: "Assign Department Heads",
      icon: UserCheck,
      description: "Set department managers",
    },
  ],

  "Designation Management": [
    {
      id: "designation_view",
      label: "View Designations",
      icon: FileText,
      description: "View all job designations",
    },
    {
      id: "designation_create",
      label: "Create Designations",
      icon: Plus,
      description: "Add new job titles",
    },
    {
      id: "designation_edit",
      label: "Edit Designations",
      icon: Edit,
      description: "Modify designation details",
    },
    {
      id: "designation_delete",
      label: "Delete Designations",
      icon: Trash2,
      description: "Remove designations",
    },
  ],

  "Financial Management": [
    {
      id: "salary_view_all",
      label: "View All Salaries",
      icon: DollarSign,
      description: "Access all salary information",
    },
    {
      id: "salary_view_own",
      label: "View Own Salary",
      icon: Wallet,
      description: "View personal salary details",
    },
    {
      id: "salary_process",
      label: "Process Payroll",
      icon: FileCheck,
      description: "Generate and process salary payments",
    },
    {
      id: "salary_edit",
      label: "Edit Salary Structure",
      icon: Edit,
      description: "Modify salary components",
    },
    {
      id: "expenses_view_all",
      label: "View All Expenses",
      icon: Eye,
      description: "View all expense claims",
    },
    {
      id: "expenses_submit",
      label: "Submit Expenses",
      icon: Plus,
      description: "Submit expense reimbursement requests",
    },
    {
      id: "expenses_approve",
      label: "Approve Expenses",
      icon: UserCheck,
      description: "Approve or reject expense claims",
    },
  ],

  "Policy & Compliance": [
    {
      id: "terms_view",
      label: "View Terms & Conditions",
      icon: FileCheck,
      description: "Access employment terms",
    },
    {
      id: "terms_manage",
      label: "Manage Terms & Conditions",
      icon: Edit,
      description: "Create and edit employment terms",
    },
    {
      id: "company_policy_view",
      label: "View Company Policies",
      icon: BookOpen,
      description: "Access company policy documents",
    },
    {
      id: "company_policy_manage",
      label: "Manage Company Policies",
      icon: Edit,
      description: "Create and update policies",
    },
    {
      id: "hr_policy_view",
      label: "View HR Policies",
      icon: ClipboardList,
      description: "Access HR policy documents",
    },
    {
      id: "hr_policy_manage",
      label: "Manage HR Policies",
      icon: Edit,
      description: "Create and update HR policies",
    },
  ],

  Recruitment: [
    {
      id: "job_view",
      label: "View Job Postings",
      icon: Briefcase,
      description: "View all job openings",
    },
    {
      id: "job_create",
      label: "Create Job Postings",
      icon: Plus,
      description: "Post new job openings",
    },
    {
      id: "job_edit",
      label: "Edit Job Postings",
      icon: Edit,
      description: "Modify job descriptions",
    },
    {
      id: "job_delete",
      label: "Delete Job Postings",
      icon: Trash2,
      description: "Remove job postings",
    },
    {
      id: "job_applications",
      label: "View Applications",
      icon: FileText,
      description: "Access candidate applications",
    },
    {
      id: "job_shortlist",
      label: "Shortlist Candidates",
      icon: UserCheck,
      description: "Manage candidate pipeline",
    },
  ],

  "Communication Tools": [
    {
      id: "catalogs_view",
      label: "View Catalogs",
      icon: BarChart,
      description: "Access product/service catalogs",
    },
    {
      id: "catalogs_manage",
      label: "Manage Catalogs",
      icon: Edit,
      description: "Create and edit catalogs",
    },
    {
      id: "messenger_use",
      label: "Use Messenger",
      icon: MessageSquare,
      description: "Send and receive internal messages",
    },
    {
      id: "messenger_broadcast",
      label: "Broadcast Messages",
      icon: Megaphone,
      description: "Send messages to multiple users",
    },
    {
      id: "notes_create",
      label: "Create Notes",
      icon: StickyNote,
      description: "Create personal notes",
    },
    {
      id: "notes_share",
      label: "Share Notes",
      icon: Users,
      description: "Share notes with team members",
    },
    {
      id: "announcement_view",
      label: "View Announcements",
      icon: Bell,
      description: "Read company announcements",
    },
    {
      id: "announcement_create",
      label: "Create Announcements",
      icon: Megaphone,
      description: "Post company-wide announcements",
    },
  ],

  "Task Management": [
    {
      id: "todo_view_own",
      label: "View Own Tasks",
      icon: CheckSquare,
      description: "View personal to-do lists",
    },
    {
      id: "todo_view_team",
      label: "View Team Tasks",
      icon: Users,
      description: "View team member tasks",
    },
    {
      id: "todo_create",
      label: "Create Tasks",
      icon: Plus,
      description: "Create new tasks",
    },
    {
      id: "todo_assign",
      label: "Assign Tasks",
      icon: UserCheck,
      description: "Assign tasks to team members",
    },
    {
      id: "todo_edit",
      label: "Edit Tasks",
      icon: Edit,
      description: "Modify task details",
    },
    {
      id: "todo_delete",
      label: "Delete Tasks",
      icon: Trash2,
      description: "Remove tasks",
    },
  ],

  "Financial Documents": [
    {
      id: "quotation_view",
      label: "View Quotations",
      icon: FileText,
      description: "Access quotation documents",
    },
    {
      id: "quotation_create",
      label: "Create Quotations",
      icon: Plus,
      description: "Generate new quotations",
    },
    {
      id: "quotation_edit",
      label: "Edit Quotations",
      icon: Edit,
      description: "Modify quotation details",
    },
    {
      id: "quotation_approve",
      label: "Approve Quotations",
      icon: UserCheck,
      description: "Approve quotations for sending",
    },
    {
      id: "invoice_view",
      label: "View Invoices",
      icon: FileText,
      description: "Access invoice records",
    },
    {
      id: "invoice_create",
      label: "Create Invoices",
      icon: Plus,
      description: "Generate new invoices",
    },
    {
      id: "invoice_edit",
      label: "Edit Invoices",
      icon: Edit,
      description: "Modify invoice details",
    },
    {
      id: "invoice_send",
      label: "Send Invoices",
      icon: Mail,
      description: "Email invoices to clients",
    },
    {
      id: "invoice_payment",
      label: "Record Payments",
      icon: DollarSign,
      description: "Mark invoices as paid",
    },
  ],

  "System Administration": [
    {
      id: "admin_full_access",
      label: "Full Administrator Access",
      icon: Shield,
      description: "Complete system control",
    },
    {
      id: "settings_view",
      label: "View System Settings",
      icon: Settings,
      description: "Access system configuration",
    },
    {
      id: "settings_edit",
      label: "Edit System Settings",
      icon: Edit,
      description: "Modify system configuration",
    },
    {
      id: "database_access",
      label: "Database Access",
      icon: Database,
      description: "Direct database operations",
    },
    {
      id: "user_management",
      label: "Manage Users",
      icon: Users,
      description: "Create and manage user accounts",
    },
    {
      id: "role_management",
      label: "Manage Roles",
      icon: Shield,
      description: "Create and assign user roles",
    },
    {
      id: "permission_management",
      label: "Manage Permissions",
      icon: Lock,
      description: "Configure system permissions",
    },
    {
      id: "audit_logs",
      label: "View Audit Logs",
      icon: FileText,
      description: "Access system activity logs",
    },
    {
      id: "backup_restore",
      label: "Backup & Restore",
      icon: Database,
      description: "Manage system backups",
    },
    {
      id: "reports_all",
      label: "Access All Reports",
      icon: FileSpreadsheet,
      description: "View comprehensive system reports",
    },
    {
      id: "export_all_data",
      label: "Export All Data",
      icon: Download,
      description: "Download complete system data",
    },
  ],
};

/**
 * Initial employee data with extended information
 */
export const initialEmployees = [
  {
    id: 1,
    name: "John Doe",
    designation: "Senior Developer",
    projects: 12,
    done: 8,
    progress: 3,
    productivity: 85,
    image: "https://i.pravatar.cc/150?img=1",
    salary: 85000,
    joinDate: "2020-03-15",
    department: "Engineering",
    email: "john.doe@company.com",
    phone: "+1-555-0101",
  },
  {
    id: 2,
    name: "Sarah Smith",
    designation: "UI/UX Designer",
    projects: 8,
    done: 6,
    progress: 2,
    productivity: 75,
    image: "https://i.pravatar.cc/150?img=2",
    salary: 70000,
    joinDate: "2021-06-20",
    department: "Design",
    email: "sarah.smith@company.com",
    phone: "+1-555-0102",
  },
  {
    id: 3,
    name: "Mike Johnson",
    designation: "Project Manager",
    projects: 15,
    done: 10,
    progress: 4,
    productivity: 90,
    image: "https://i.pravatar.cc/150?img=3",
    salary: 95000,
    joinDate: "2019-01-10",
    department: "Management",
    email: "mike.johnson@company.com",
    phone: "+1-555-0103",
  },
  {
    id: 4,
    name: "Emily Brown",
    designation: "Backend Developer",
    projects: 10,
    done: 7,
    progress: 2,
    productivity: 70,
    image: "https://i.pravatar.cc/150?img=4",
    salary: 78000,
    joinDate: "2021-09-05",
    department: "Engineering",
    email: "emily.brown@company.com",
    phone: "+1-555-0104",
  },
  {
    id: 5,
    name: "David Wilson",
    designation: "QA Engineer",
    projects: 9,
    done: 5,
    progress: 3,
    productivity: 55,
    image: "https://i.pravatar.cc/150?img=5",
    salary: 65000,
    joinDate: "2022-02-14",
    department: "Quality Assurance",
    email: "david.wilson@company.com",
    phone: "+1-555-0105",
  },
  {
    id: 6,
    name: "Lisa Anderson",
    designation: "Frontend Developer",
    projects: 11,
    done: 9,
    progress: 2,
    productivity: 82,
    image: "https://i.pravatar.cc/150?img=6",
    salary: 75000,
    joinDate: "2020-11-30",
    department: "Engineering",
    email: "lisa.anderson@company.com",
    phone: "+1-555-0106",
  },
  {
    id: 7,
    name: "Robert Martinez",
    designation: "Sales Manager",
    projects: 14,
    done: 11,
    progress: 3,
    productivity: 88,
    image: "https://i.pravatar.cc/150?img=7",
    salary: 90000,
    joinDate: "2019-07-22",
    department: "Sales",
    email: "robert.martinez@company.com",
    phone: "+1-555-0107",
  },
  {
    id: 8,
    name: "Jennifer Taylor",
    designation: "HR Manager",
    projects: 7,
    done: 5,
    progress: 2,
    productivity: 78,
    image: "https://i.pravatar.cc/150?img=8",
    salary: 82000,
    joinDate: "2020-04-18",
    department: "Human Resources",
    email: "jennifer.taylor@company.com",
    phone: "+1-555-0108",
  },
];

/**
 * Predefined role templates with common permission sets
 */
export const roleTemplates = {
  administrator: {
    name: "System Administrator",
    description: "Full system access and control",
    permissions: [
      "admin_full_access",
      "settings_edit",
      "database_access",
      "user_management",
    ],
  },
  salesManager: {
    name: "Sales Manager",
    description: "Manage sales team and pipeline",
    permissions: [
      "crm_dashboard_view",
      "leads_view_all",
      "leads_assign",
      "pipeline_view",
      "clients_view_all",
      "team_view",
      "team_assign_members",
    ],
  },
  hrManager: {
    name: "HR Manager",
    description: "Human resources management",
    permissions: [
      "hrm_dashboard_view",
      "employee_view_all",
      "employee_create",
      "attendance_view_all",
      "leave_approve",
      "salary_view_all",
      "job_create",
    ],
  },
  teamLead: {
    name: "Team Lead",
    description: "Manage team and assign tasks",
    permissions: [
      "leads_view_own",
      "leads_edit",
      "clients_view_own",
      "team_view",
      "todo_view_team",
      "todo_assign",
    ],
  },
  salesRep: {
    name: "Sales Representative",
    description: "Basic CRM access",
    permissions: [
      "crm_dashboard_view",
      "leads_view_own",
      "leads_edit",
      "leads_contact",
      "clients_view_own",
      "pipeline_view",
    ],
  },
  employee: {
    name: "Standard Employee",
    description: "Basic employee access",
    permissions: [
      "attendance_view_own",
      "leave_view_own",
      "leave_apply",
      "todo_view_own",
      "notes_create",
      "messenger_use",
    ],
  },
};
